"use client";

import { ProvenanceBadge } from "@provenancekit/ui";
import { PreviewShell } from "../../components/preview-shell";
import { mockBundle } from "../../lib/mock-data";

function SectionLabel({ children }: { children: string }) {
  return (
    <p
      className="text-xs font-semibold uppercase tracking-widest mb-3"
      style={{ color: "var(--pk-muted-foreground)" }}
    >
      {children}
    </p>
  );
}

export function BadgePreviewClient() {
  return (
    <PreviewShell className="p-10 flex flex-col items-center gap-12">

      {/* Floating over image — primary use case */}
      <div className="flex flex-col items-center">
        <SectionLabel>Floating over content</SectionLabel>
        <div className="flex items-end gap-8">
          {/* Rich gradient image simulation */}
          <div className="flex flex-col items-center gap-2">
            <ProvenanceBadge bundle={mockBundle} position="bottom-right" size="md">
              <div
                className="w-56 h-36 rounded-xl flex items-center justify-center text-xs font-medium"
                style={{
                  background: "linear-gradient(135deg, #1e3a5f 0%, #2d1b4e 50%, #1a3a2e 100%)",
                  color: "rgba(255,255,255,0.5)",
                }}
              >
                AI-generated image
              </div>
            </ProvenanceBadge>
            <span className="text-[11px]" style={{ color: "var(--pk-muted-foreground)" }}>bottom-right (default)</span>
          </div>

          {/* Top-left position */}
          <div className="flex flex-col items-center gap-2">
            <ProvenanceBadge bundle={mockBundle} position="top-left" size="md">
              <div
                className="w-56 h-36 rounded-xl flex items-center justify-center text-xs font-medium"
                style={{
                  background: "linear-gradient(135deg, #3a1e1e 0%, #4e2d1b 50%, #1e3a3a 100%)",
                  color: "rgba(255,255,255,0.5)",
                }}
              >
                AI-generated image
              </div>
            </ProvenanceBadge>
            <span className="text-[11px]" style={{ color: "var(--pk-muted-foreground)" }}>top-left</span>
          </div>
        </div>
      </div>

      {/* Inline variant — for text content */}
      <div className="flex flex-col items-center">
        <SectionLabel>Inline variant</SectionLabel>
        <div
          className="rounded-xl px-5 py-4 max-w-sm w-full"
          style={{
            background: "var(--pk-surface-muted)",
            border: "1px solid var(--pk-surface-border)",
          }}
        >
          <ProvenanceBadge bundle={mockBundle} variant="inline" size="sm">
            <span style={{ color: "var(--pk-foreground)", fontSize: "0.875rem" }}>
              This poem was generated by Claude Sonnet 4.6
            </span>
          </ProvenanceBadge>
          <p
            className="mt-2 text-sm leading-relaxed"
            style={{ color: "var(--pk-muted-foreground)" }}
          >
            In fields of gold and skies so blue,<br />
            The morning light breaks ever new…
          </p>
        </div>
      </div>

      {/* Size variants */}
      <div className="flex flex-col items-center">
        <SectionLabel>Sizes</SectionLabel>
        <div className="flex items-end gap-8">
          {(["sm", "md", "lg"] as const).map((size) => (
            <div key={size} className="flex flex-col items-center gap-2">
              <ProvenanceBadge bundle={mockBundle} size={size} position="bottom-right">
                <div
                  className="rounded-xl"
                  style={{
                    width: size === "sm" ? 64 : size === "md" ? 88 : 112,
                    height: size === "sm" ? 64 : size === "md" ? 88 : 112,
                    background: "var(--pk-surface-muted)",
                    border: "1px solid var(--pk-surface-border)",
                  }}
                />
              </ProvenanceBadge>
              <span className="text-xs font-medium" style={{ color: "var(--pk-muted-foreground)" }}>
                {size}
              </span>
            </div>
          ))}
        </div>
      </div>

    </PreviewShell>
  );
}
