// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/**
 * @title IProvenanceProvider
 * @author ProvenanceKit
 * @notice The minimal standard interface for provenance systems
 * @dev This is THE STANDARD. Any contract emitting these events with this interface
 *      is considered ProvenanceKit compatible and part of the universal provenance layer.
 *
 *      Design principles:
 *      - Minimal: Only what's absolutely necessary
 *      - Stable: This interface should rarely change
 *      - Universal: Works for any provenance use case
 *
 *      Following the EAA (Entity-Action-Attribution) model from provenancekit/eaa-types
 */
interface IProvenanceProvider {
    /*//////////////////////////////////////////////////////////////
                              STANDARD EVENTS
    //////////////////////////////////////////////////////////////*/

    /**
     * @notice MUST be emitted when an action is recorded
     * @dev This is the core provenance event. ALL implementations MUST emit this
     *      exactly as specified to be considered compatible.
     *
     *      Content references (inputs/outputs) are strings that identify content.
     *      Recommended format: IPFS CIDs (e.g., "bafyabc...")
     *      Also supported: Arweave IDs, URLs with integrity hashes, or custom schemes.
     *      The off-chain SDK handles conversion to/from ContentReference objects.
     *
     * @param actionId Unique identifier for the action (generated by implementation)
     * @param actionType Type of action: "create", "transform", "aggregate", "verify", or custom
     * @param performer Address that recorded the action (msg.sender)
     * @param inputs Array of input content references (can be empty for "create")
     * @param outputs Array of output content references (the results of the action)
     * @param timestamp Block timestamp when the action was recorded
     */
    event ActionRecorded(
        bytes32 indexed actionId,
        string actionType,
        address indexed performer,
        string[] inputs,
        string[] outputs,
        uint256 timestamp
    );

    /**
     * @notice Emitted when a resource is registered
     * @dev Optional but recommended. Links a content reference to its creating action.
     *
     * @param contentRef Content reference (IPFS CID recommended, but URLs/hashes supported)
     * @param resourceType Type: "text", "image", "audio", "video", "code", "data", "model"
     * @param creator Address that registered the resource
     * @param rootAction The action that created this resource
     * @param timestamp Block timestamp when registered
     */
    event ResourceRegistered(
        string indexed contentRef,
        string resourceType,
        address indexed creator,
        bytes32 rootAction,
        uint256 timestamp
    );

    /**
     * @notice Emitted when an entity is registered
     * @dev Optional. Maps an address to an off-chain identity.
     *
     * @param entityAddress On-chain address
     * @param entityId Off-chain identifier (DID, UUID, etc.)
     * @param entityRole Role: "human", "ai", "organization"
     * @param timestamp Block timestamp when registered
     */
    event EntityRegistered(
        address indexed entityAddress,
        string entityId,
        string entityRole,
        uint256 timestamp
    );

    /**
     * @notice Emitted when attribution is recorded for a resource
     * @dev Optional. Records who contributed to a resource.
     *
     * @param contentRef Content reference (CID, URL, or other identifier)
     * @param entityAddress Address receiving attribution
     * @param role Attribution role: "creator", "contributor", "source"
     * @param timestamp Block timestamp when recorded
     */
    event AttributionRecorded(
        string indexed contentRef,
        address indexed entityAddress,
        string role,
        uint256 timestamp
    );

    /**
     * @notice Emitted when attribution is recorded for an action
     * @dev Optional. Records who was involved in performing an action.
     *      Use this for action-level attribution (W3C PROV Association).
     *
     * @param actionId The action being attributed
     * @param entityAddress Address receiving attribution
     * @param role Attribution role: "creator", "contributor", "source"
     * @param timestamp Block timestamp when recorded
     */
    event ActionAttributionRecorded(
        bytes32 indexed actionId,
        address indexed entityAddress,
        string role,
        uint256 timestamp
    );

    /*//////////////////////////////////////////////////////////////
                            REQUIRED FUNCTIONS
    //////////////////////////////////////////////////////////////*/

    /**
     * @notice Record an action to the provenance system
     * @dev This is the ONLY required function. Everything else is optional.
     *
     * @param actionType Type of action being performed
     * @param inputs Array of input content references (CIDs recommended)
     * @param outputs Array of output content references (CIDs recommended)
     * @return actionId Unique identifier for the recorded action
     */
    function recordAction(
        string calldata actionType,
        string[] calldata inputs,
        string[] calldata outputs
    ) external returns (bytes32 actionId);

    /**
     * @notice Check if an action has been recorded
     * @param actionId The action identifier to check
     * @return True if the action exists
     */
    function actionExists(bytes32 actionId) external view returns (bool);

    /*//////////////////////////////////////////////////////////////
                           ERC-165 SUPPORT
    //////////////////////////////////////////////////////////////*/

    /**
     * @notice Check if contract implements an interface
     * @dev See ERC-165. Use this to verify ProvenanceKit compatibility.
     *      interfaceId for IProvenanceProvider: 0x... (to be calculated)
     *
     * @param interfaceId The interface identifier to check
     * @return True if the interface is supported
     */
    function supportsInterface(bytes4 interfaceId) external view returns (bool);
}
