// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/**
 * @title IProvenanceProvider
 * @author ProvenanceKit
 * @notice The minimal standard interface for provenance systems
 * @dev This is THE STANDARD. Any contract emitting these events with this interface
 *      is considered ProvenanceKit compatible and part of the universal provenance layer.
 *
 *      Design principles:
 *      - Minimal: Only what's absolutely necessary
 *      - Stable: This interface should rarely change
 *      - Universal: Works for any provenance use case
 *
 *      Following the EAA (Entity-Action-Attribution) model from provenancekit/eaa-types
 */
interface IProvenanceProvider {
    /*//////////////////////////////////////////////////////////////
                              STANDARD EVENTS
    //////////////////////////////////////////////////////////////*/

    /**
     * @notice MUST be emitted when an action is recorded
     * @dev This is the core provenance event. ALL implementations MUST emit this
     *      exactly as specified to be considered compatible.
     *
     * @param actionId Unique identifier for the action (generated by implementation)
     * @param actionType Type of action: "create", "transform", "aggregate", "verify", or custom
     * @param performer Address that recorded the action (msg.sender)
     * @param inputs Array of input resource CIDs (can be empty for "create")
     * @param outputs Array of output resource CIDs (the results of the action)
     * @param timestamp Block timestamp when the action was recorded
     */
    event ActionRecorded(
        bytes32 indexed actionId,
        string actionType,
        address indexed performer,
        string[] inputs,
        string[] outputs,
        uint256 timestamp
    );

    /**
     * @notice Emitted when a resource is registered
     * @dev Optional but recommended. Links a CID to its creating action.
     *
     * @param cid Content identifier (IPFS CID)
     * @param resourceType Type: "text", "image", "audio", "video", "code", "data", "model"
     * @param creator Address that registered the resource
     * @param rootAction The action that created this resource
     * @param timestamp Block timestamp when registered
     */
    event ResourceRegistered(
        string indexed cid,
        string resourceType,
        address indexed creator,
        bytes32 rootAction,
        uint256 timestamp
    );

    /**
     * @notice Emitted when an entity is registered
     * @dev Optional. Maps an address to an off-chain identity.
     *
     * @param entityAddress On-chain address
     * @param entityId Off-chain identifier (DID, UUID, etc.)
     * @param entityRole Role: "human", "ai", "organization"
     * @param timestamp Block timestamp when registered
     */
    event EntityRegistered(
        address indexed entityAddress,
        string entityId,
        string entityRole,
        uint256 timestamp
    );

    /**
     * @notice Emitted when attribution is recorded
     * @dev Optional. Records who contributed to a resource.
     *
     * @param cid Resource CID being attributed
     * @param entityAddress Address receiving attribution
     * @param role Attribution role: "creator", "contributor", "source"
     * @param timestamp Block timestamp when recorded
     */
    event AttributionRecorded(
        string indexed cid,
        address indexed entityAddress,
        string role,
        uint256 timestamp
    );

    /*//////////////////////////////////////////////////////////////
                            REQUIRED FUNCTIONS
    //////////////////////////////////////////////////////////////*/

    /**
     * @notice Record an action to the provenance system
     * @dev This is the ONLY required function. Everything else is optional.
     *
     * @param actionType Type of action being performed
     * @param inputs Array of input resource CIDs
     * @param outputs Array of output resource CIDs
     * @return actionId Unique identifier for the recorded action
     */
    function recordAction(
        string calldata actionType,
        string[] calldata inputs,
        string[] calldata outputs
    ) external returns (bytes32 actionId);

    /**
     * @notice Check if an action has been recorded
     * @param actionId The action identifier to check
     * @return True if the action exists
     */
    function actionExists(bytes32 actionId) external view returns (bool);

    /*//////////////////////////////////////////////////////////////
                           ERC-165 SUPPORT
    //////////////////////////////////////////////////////////////*/

    /**
     * @notice Check if contract implements an interface
     * @dev See ERC-165. Use this to verify ProvenanceKit compatibility.
     *      interfaceId for IProvenanceProvider: 0x... (to be calculated)
     *
     * @param interfaceId The interface identifier to check
     * @return True if the interface is supported
     */
    function supportsInterface(bytes4 interfaceId) external view returns (bool);
}
