import type { Metadata } from "next";
import { PrivyProvider } from "@/components/providers/privy-provider";
import { QueryProvider } from "@/components/ui/query-provider";
import { ProvenanceKitProvider } from "@/components/providers/pk-provider";
import "./globals.css";
import { Space_Grotesk } from "next/font/google";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-space-grotesk",
  display: "swap",
});

const baseUrl = "https://www.provenancekit.com";

export const metadata: Metadata = {
  metadataBase: new URL(baseUrl),
  title: {
    default:
      "ProvenanceKit — Content Provenance toolkit for Human-AI Creations",
    template: "%s | ProvenanceKit",
  },
  description:
    "Standard toolkit for Human-AI content provenance. Record, verify, and communicate how content was created — onchain anchoring, C2PA support, and programmable attribution.",
  keywords: [
    "content provenance",
    "AI provenance",
    "Human-AI content",
    "provenance toolkit",
    "content attribution",
    "AI attribution",
    "onchain provenance",
    "C2PA",
    "EAA",
    "content transparency",
    "AI disclosure",
    "open source provenance",
  ],
  alternates: {
    canonical: baseUrl,
  },
  openGraph: {
    type: "website",
    url: baseUrl,
    siteName: "ProvenanceKit",
    title: "ProvenanceKit —  Content Provenance Toolkit for Human-AI creations",
    description:
      "Record, verify, and communicate how Human-AI content was created. Onchain anchoring, C2PA support, privacy extensions, and programmable attribution — open source.",
    locale: "en_US",
    // og:image is generated by app/opengraph-image.tsx (file convention takes precedence)
  },
  twitter: {
    card: "summary_large_image",
    site: "@provenancekit",
    creator: "@provenancekit",
    title:
      "ProvenanceKit — Open Source Content Provenance Toolkit for Human-AI Works",
    description:
      "Record, verify, and communicate how Human-AI content was created. Onchain anchoring, C2PA support, and programmable attribution — open source.",
    // twitter:image is generated by app/twitter-image.tsx (file convention takes precedence)
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-snippet": -1,
      "max-image-preview": "large",
      "max-video-preview": -1,
    },
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning className={spaceGrotesk.variable}>
      <body>
        <PrivyProvider>
          <QueryProvider>
            {/*
             * ProvenanceKitProvider points at /api/pk-proxy — adds Authorization
             * server-side so PROVENANCEKIT_API_KEY never reaches the browser.
             * All @provenancekit/ui interactive components (ProvenanceGraph,
             * ProvenanceBundleView, ProvenanceSearch, FileUploadZone) work
             * transparently through this proxy.
             */}
            <ProvenanceKitProvider apiUrl="/api/pk-proxy" apiKey="">
              {children}
            </ProvenanceKitProvider>
          </QueryProvider>
        </PrivyProvider>
      </body>
    </html>
  );
}
