steps:
  - name: node
    dir: './apps/provenancekit-api'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install -g pnpm
        pnpm install
        pnpm build
  - name: 'gcr.io/cloud-builders/docker'
    dir: './apps/provenancekit-api'
    args:
      [
        'build',
        '-t',
        'europe-west1-docker.pkg.dev/$PROJECT_ID/provenancekit/provenancekit-api:$SHORT_SHA',
        '-f',
        'Dockerfile',
        '.',
      ]

  - name: 'gcr.io/cloud-builders/docker'
    dir: '.'
    args:
      [
        'tag',
        'europe-west1-docker.pkg.dev/$PROJECT_ID/provenancekit/provenancekit-api:$SHORT_SHA',
        'europe-west1-docker.pkg.dev/$PROJECT_ID/provenancekit/provenancekit-api:prod',
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'europe-west1-docker.pkg.dev/$PROJECT_ID/provenancekit/provenancekit-api',
        '--all-tags',
      ]

  - name: 'gcr.io/cloud-builders/gcloud'

    entrypoint: gcloud

    args:
      - run
      - deploy
      - arttribute-provenancekit-api-prod
      - --region=europe-west1
      - --platform=managed
      - --image=europe-west1-docker.pkg.dev/$PROJECT_ID/provenancekit/provenancekit-api:prod

    timeout: 1800s
# options:
#   machineType: "E2_MEDIUM"
