/**
 * Git hooks generator for automatic provenance recording.
 *
 * Generates git hooks that automatically record provenance
 * for commits, pushes, and other git operations.
 *
 * @packageDocumentation
 */

import * as fs from "fs";
import * as path from "path";
import type { GitHookType, GitHookConfig, GeneratedHook } from "../types.js";
import { GitError } from "../types.js";

/*─────────────────────────────────────────────────────────────*\
 | Hook Templates                                               |
\*─────────────────────────────────────────────────────────────*/

/**
 * Template for post-commit hook.
 */
function generatePostCommitScript(config: GitHookConfig): string {
  const { storageUrl, contractAddress, chainId, aiDetection = true, postScript, envVars = {} } = config;

  const envLines = Object.entries(envVars)
    .map(([key, value]) => `export ${key}="${value}"`)
    .join("\n");

  return `#!/bin/bash
# ProvenanceKit post-commit hook
# Generated by @provenancekit/git
# This hook records provenance for each commit

set -e

${envLines}

# Get the commit hash
COMMIT_SHA=$(git rev-parse HEAD)
REPO_PATH=$(git rev-parse --show-toplevel)

echo "Recording provenance for commit $COMMIT_SHA..."

# Run the provenance recording
npx @provenancekit/git record-commit \\
  --commit "$COMMIT_SHA" \\
  --repo "$REPO_PATH" \\
  ${aiDetection ? "--detect-ai" : ""} \\
  ${storageUrl ? `--storage-url "${storageUrl}"` : ""} \\
  ${contractAddress ? `--contract "${contractAddress}"` : ""} \\
  ${chainId ? `--chain-id ${chainId}` : ""}

${postScript ?? ""}

echo "Provenance recorded successfully."
`;
}

/**
 * Template for prepare-commit-msg hook.
 * Adds AI co-author line if AI assistance is detected.
 */
function generatePrepareCommitMsgScript(config: GitHookConfig): string {
  const { envVars = {} } = config;

  const envLines = Object.entries(envVars)
    .map(([key, value]) => `export ${key}="${value}"`)
    .join("\n");

  return `#!/bin/bash
# ProvenanceKit prepare-commit-msg hook
# Generated by @provenancekit/git
# This hook adds AI co-author information if detected

${envLines}

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2

# Only modify for regular commits, not merges, squashes, etc.
if [ -n "$COMMIT_SOURCE" ] && [ "$COMMIT_SOURCE" != "message" ]; then
  exit 0
fi

# Check for AI tool indicators in the environment or session
AI_TOOL=""

# Check for Cursor
if [ -n "$CURSOR_SESSION" ] || [ -d ".cursor" ]; then
  AI_TOOL="Cursor"
fi

# Check for GitHub Copilot
if [ -n "$GITHUB_COPILOT_ENABLED" ]; then
  AI_TOOL="GitHub Copilot"
fi

# Check for Aider
if [ -n "$AIDER_SESSION" ] || [ -f ".aider" ]; then
  AI_TOOL="Aider"
fi

# Add co-author line if AI tool detected and not already present
if [ -n "$AI_TOOL" ]; then
  if ! grep -q "Co-authored-by:.*$AI_TOOL" "$COMMIT_MSG_FILE"; then
    echo "" >> "$COMMIT_MSG_FILE"
    echo "Co-authored-by: $AI_TOOL <ai-assistant@provenancekit.org>" >> "$COMMIT_MSG_FILE"
  fi
fi
`;
}

/**
 * Template for commit-msg hook.
 * Validates commit message format or adds provenance metadata.
 */
function generateCommitMsgScript(config: GitHookConfig): string {
  const { envVars = {} } = config;

  const envLines = Object.entries(envVars)
    .map(([key, value]) => `export ${key}="${value}"`)
    .join("\n");

  return `#!/bin/bash
# ProvenanceKit commit-msg hook
# Generated by @provenancekit/git
# This hook can validate or enhance commit messages

${envLines}

COMMIT_MSG_FILE=$1

# Read the commit message
COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")

# You can add custom validation or enhancement here
# For now, this hook just passes through

exit 0
`;
}

/**
 * Template for pre-commit hook.
 */
function generatePreCommitScript(config: GitHookConfig): string {
  const { envVars = {} } = config;

  const envLines = Object.entries(envVars)
    .map(([key, value]) => `export ${key}="${value}"`)
    .join("\n");

  return `#!/bin/bash
# ProvenanceKit pre-commit hook
# Generated by @provenancekit/git
# This hook runs before each commit

${envLines}

# Add any pre-commit checks here
# For example, you could verify that certain files are present

exit 0
`;
}

/**
 * Template for pre-push hook.
 */
function generatePrePushScript(config: GitHookConfig): string {
  const { storageUrl, contractAddress, chainId, envVars = {} } = config;

  const envLines = Object.entries(envVars)
    .map(([key, value]) => `export ${key}="${value}"`)
    .join("\n");

  return `#!/bin/bash
# ProvenanceKit pre-push hook
# Generated by @provenancekit/git
# This hook records provenance before pushing

set -e

${envLines}

REMOTE=$1
URL=$2

# Read the pushed commits
while read local_ref local_sha remote_ref remote_sha; do
  if [ "$local_sha" = "0000000000000000000000000000000000000000" ]; then
    # Branch deletion, skip
    continue
  fi

  if [ "$remote_sha" = "0000000000000000000000000000000000000000" ]; then
    # New branch, record all commits
    RANGE="$local_sha"
  else
    # Existing branch, record new commits
    RANGE="$remote_sha..$local_sha"
  fi

  echo "Recording provenance for commits: $RANGE"

  # Record each commit in the range
  for COMMIT in $(git rev-list --reverse $RANGE); do
    npx @provenancekit/git record-commit \\
      --commit "$COMMIT" \\
      ${storageUrl ? `--storage-url "${storageUrl}"` : ""} \\
      ${contractAddress ? `--contract "${contractAddress}"` : ""} \\
      ${chainId ? `--chain-id ${chainId}` : ""}
  done
done

exit 0
`;
}

/*─────────────────────────────────────────────────────────────*\
 | Hook Generation                                              |
\*─────────────────────────────────────────────────────────────*/

/**
 * Generate a git hook script.
 *
 * @param config - Hook configuration
 * @returns Generated hook with script content
 *
 * @example
 * ```typescript
 * const hook = generateHook({
 *   hookType: "post-commit",
 *   storageUrl: "https://api.provenancekit.org/storage",
 *   aiDetection: true,
 * });
 *
 * console.log(hook.script);
 * ```
 */
export function generateHook(config: GitHookConfig): GeneratedHook {
  let script: string;

  switch (config.hookType) {
    case "post-commit":
      script = generatePostCommitScript(config);
      break;
    case "prepare-commit-msg":
      script = generatePrepareCommitMsgScript(config);
      break;
    case "commit-msg":
      script = generateCommitMsgScript(config);
      break;
    case "pre-commit":
      script = generatePreCommitScript(config);
      break;
    case "pre-push":
      script = generatePrePushScript(config);
      break;
    default:
      throw new GitError(
        `Unsupported hook type: ${config.hookType}`,
        "INVALID_OPTIONS",
        { hookType: config.hookType }
      );
  }

  return {
    hookType: config.hookType,
    script,
    installPath: `.git/hooks/${config.hookType}`,
  };
}

/**
 * Install a git hook in a repository.
 *
 * @param repoPath - Path to the repository
 * @param hook - Generated hook to install
 * @param options - Installation options
 *
 * @example
 * ```typescript
 * const hook = generateHook({ hookType: "post-commit" });
 * await installHook("/path/to/repo", hook);
 * ```
 */
export async function installHook(
  repoPath: string,
  hook: GeneratedHook,
  options: { backup?: boolean; force?: boolean } = {}
): Promise<void> {
  const { backup = true, force = false } = options;

  const hookPath = path.join(repoPath, hook.installPath);
  const hooksDir = path.dirname(hookPath);

  // Ensure hooks directory exists
  if (!fs.existsSync(hooksDir)) {
    fs.mkdirSync(hooksDir, { recursive: true });
  }

  // Check if hook already exists
  if (fs.existsSync(hookPath)) {
    if (!force) {
      throw new GitError(
        `Hook already exists: ${hook.hookType}. Use force option to overwrite.`,
        "INVALID_OPTIONS",
        { hookType: hook.hookType, path: hookPath }
      );
    }

    // Backup existing hook
    if (backup) {
      const backupPath = `${hookPath}.backup.${Date.now()}`;
      fs.copyFileSync(hookPath, backupPath);
    }
  }

  // Write the hook
  fs.writeFileSync(hookPath, hook.script, { mode: 0o755 });
}

/**
 * Uninstall a git hook from a repository.
 *
 * @param repoPath - Path to the repository
 * @param hookType - Type of hook to uninstall
 * @param options - Uninstallation options
 */
export async function uninstallHook(
  repoPath: string,
  hookType: GitHookType,
  options: { restoreBackup?: boolean } = {}
): Promise<void> {
  const { restoreBackup = false } = options;

  const hookPath = path.join(repoPath, ".git/hooks", hookType);

  if (!fs.existsSync(hookPath)) {
    return; // Hook doesn't exist, nothing to do
  }

  // Remove the hook
  fs.unlinkSync(hookPath);

  // Optionally restore backup
  if (restoreBackup) {
    const backupFiles = fs
      .readdirSync(path.dirname(hookPath))
      .filter((f) => f.startsWith(`${hookType}.backup.`))
      .sort()
      .reverse();

    if (backupFiles.length > 0) {
      const latestBackup = path.join(path.dirname(hookPath), backupFiles[0]);
      fs.copyFileSync(latestBackup, hookPath);
      fs.chmodSync(hookPath, 0o755);
    }
  }
}

/**
 * Initialize ProvenanceKit hooks in a repository.
 *
 * Installs all recommended hooks for provenance tracking.
 *
 * @param repoPath - Path to the repository
 * @param config - Base configuration for hooks
 * @returns Array of installed hooks
 *
 * @example
 * ```typescript
 * const installed = await initializeHooks("/path/to/repo", {
 *   storageUrl: "https://api.provenancekit.org/storage",
 *   aiDetection: true,
 * });
 *
 * console.log(`Installed ${installed.length} hooks`);
 * ```
 */
export async function initializeHooks(
  repoPath: string,
  config: Omit<GitHookConfig, "hookType"> = {}
): Promise<GeneratedHook[]> {
  const hookTypes: GitHookType[] = [
    "prepare-commit-msg",
    "post-commit",
  ];

  const installed: GeneratedHook[] = [];

  for (const hookType of hookTypes) {
    const hook = generateHook({ ...config, hookType });
    await installHook(repoPath, hook, { force: true, backup: true });
    installed.push(hook);
  }

  return installed;
}

/**
 * Check if ProvenanceKit hooks are installed in a repository.
 *
 * @param repoPath - Path to the repository
 * @returns Object with hook installation status
 */
export function checkHooksInstalled(
  repoPath: string
): Record<GitHookType, boolean> {
  const hookTypes: GitHookType[] = [
    "pre-commit",
    "prepare-commit-msg",
    "commit-msg",
    "post-commit",
    "pre-push",
  ];

  const status: Record<string, boolean> = {};

  for (const hookType of hookTypes) {
    const hookPath = path.join(repoPath, ".git/hooks", hookType);

    if (fs.existsSync(hookPath)) {
      // Check if it's a ProvenanceKit hook
      const content = fs.readFileSync(hookPath, "utf-8");
      status[hookType] = content.includes("ProvenanceKit");
    } else {
      status[hookType] = false;
    }
  }

  return status as Record<GitHookType, boolean>;
}
